name: shorthand# you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.2.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple text substitution processor
description: |
  Shorthand lets to define simple symbols for substitution in a text.
  It provides a set of text expansions based on values and data sources.
  See https://github.com/rsdoiel/shorthand for details.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  shorthand:
    command: bin/shorthand
    plugs:
      - home

parts:
  shorthand:
    # See 'snapcraft plugins'
    plugin: go
    go-channel: stable
    build-environment:
        - "CGO_ENABLED" : "0"
    source-type: git
    source: https://github.com/rsdoiel/shorthand
