name: shorthand # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.2.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A simple label or macro expander
description: |
  Shorthand lets to define simple labels for substitution in a text.
  The label expansions can be literal text or data produced by shell scripts or other programs.

  See https://github.com/rsdoiel/shorthand for details.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  shorthand:
    command: bin/shorthand
    plugs:
      - home
      - removeable-media
      - desktop

parts:
  shorthand:
    # See 'snapcraft plugins'
    plugin: go
    go-channel: stable
    build-environment:
        - "CGO_ENABLED" : "1"
    source-type: git
    source: https://github.com/rsdoiel/shorthand
